from typing import List, Dict, Any

DEMO_ASSETS: List[Dict[str, Any]] = [
    {
        "id": "A-001",
        "name": "UPI Payment Gateway Core",
        "type": "Payment Gateway",
        "business_unit": "Retail Payments & Consumer Banking",
        "criticality": "Tier 1 - Mission Critical",
        "revenue_attribution_daily": 2400000.0,
        "downtime_cost_per_hour": 95000.0,
        "data_classification": "PCI-DSS / Financial",
        "eal": 2840000.0,
        "var_95": 5900000.0,
        "control_strength_pct": 68.0,
        "active_vulnerabilities": 5,
        "host_name": "pay-ingress-prod-01.bank.internal",
        "cloud_provider": "AWS",
        "status": "Critical Attention",
    },
    {
        "id": "A-002",
        "name": "Core Banking Transaction Engine",
        "type": "Core Banking",
        "business_unit": "Core Banking & Treasury Operations",
        "criticality": "Tier 1 - Mission Critical",
        "revenue_attribution_daily": 8500000.0,
        "downtime_cost_per_hour": 280000.0,
        "data_classification": "PCI-DSS / Financial",
        "eal": 4200000.0,
        "var_95": 8100000.0,
        "control_strength_pct": 74.0,
        "active_vulnerabilities": 4,
        "host_name": "cbs-ledger-node-04.mumbai.dc",
        "cloud_provider": "Hybrid On-Prem",
        "status": "At Risk",
    },
    {
        "id": "A-003",
        "name": "Customer Identity & Federation Directory",
        "type": "IAM Directory",
        "business_unit": "Digital Channels & Wealth Platform",
        "criticality": "Tier 1 - Mission Critical",
        "revenue_attribution_daily": 1200000.0,
        "downtime_cost_per_hour": 60000.0,
        "data_classification": "PII & Customer Data",
        "eal": 2100000.0,
        "var_95": 4300000.0,
        "control_strength_pct": 71.0,
        "active_vulnerabilities": 3,
        "host_name": "auth-federate-prod.okta.bank",
        "cloud_provider": "GCP",
        "status": "At Risk",
    },
    {
        "id": "A-004",
        "name": "Enterprise Analytical Data Lake (Snowflake/S3)",
        "type": "Data Lake",
        "business_unit": "Risk, Analytics & FinCrime Surveillance",
        "criticality": "Tier 2 - Business Operational",
        "revenue_attribution_daily": 450000.0,
        "downtime_cost_per_hour": 25000.0,
        "data_classification": "PII & Customer Data",
        "eal": 1450000.0,
        "var_95": 3100000.0,
        "control_strength_pct": 82.0,
        "active_vulnerabilities": 2,
        "host_name": "datalake-analytics-s3.us-east.aws",
        "cloud_provider": "AWS",
        "status": "Healthy",
    },
    {
        "id": "A-005",
        "name": "Trade Settlement & Swift Ingress Interface",
        "type": "API Gateway",
        "business_unit": "Institutional Markets & Asset Management",
        "criticality": "Tier 1 - Mission Critical",
        "revenue_attribution_daily": 3900000.0,
        "downtime_cost_per_hour": 140000.0,
        "data_classification": "PCI-DSS / Financial",
        "eal": 2650000.0,
        "var_95": 4800000.0,
        "control_strength_pct": 79.0,
        "active_vulnerabilities": 2,
        "host_name": "swift-ingress-fin.bank.int",
        "cloud_provider": "Azure",
        "status": "Healthy",
    },
    {
        "id": "A-006",
        "name": "Retail Mobile Banking Backplane",
        "type": "Customer Portal",
        "business_unit": "Retail Payments & Consumer Banking",
        "criticality": "Tier 1 - Mission Critical",
        "revenue_attribution_daily": 1800000.0,
        "downtime_cost_per_hour": 75000.0,
        "data_classification": "PCI-DSS / Financial",
        "eal": 1610000.0,
        "var_95": 2200000.0,
        "control_strength_pct": 84.0,
        "active_vulnerabilities": 2,
        "host_name": "mobile-bff-cluster.ap-south-1.aws",
        "cloud_provider": "AWS",
        "status": "Healthy",
    },
]

DEMO_VULNERABILITIES: List[Dict[str, Any]] = [
    {
        "id": "V-001",
        "cve": "CVE-2024-3400",
        "title": "Palo Alto PAN-OS Remote Command Injection",
        "severity": "Critical",
        "cvss": 10.0,
        "epss": 0.94,
        "affected_asset_id": "A-002",
        "asset_name": "Core Banking Transaction Engine",
        "business_unit": "Core Banking & Treasury Operations",
        "discovery_date": "2026-09-12",
        "estimated_financial_impact": 3450000.0,
        "remediation_cost": 25000.0,
        "status": "Open",
        "threat_vector": "Remote Code Execution",
        "recommended_action": "Apply emergency hotfix PAN-OS 11.1.2-h3 and enable Threat Prevention signature 95187.",
        "days_open": 15,
    },
    {
        "id": "V-002",
        "cve": "CVE-2024-6387",
        "title": "OpenSSH regreSSHion Signal Handler Race Condition",
        "severity": "Critical",
        "cvss": 9.8,
        "epss": 0.72,
        "affected_asset_id": "A-001",
        "asset_name": "UPI Payment Gateway Core",
        "business_unit": "Retail Payments & Consumer Banking",
        "discovery_date": "2026-09-18",
        "estimated_financial_impact": 2840000.0,
        "remediation_cost": 15000.0,
        "status": "Open",
        "threat_vector": "Remote Code Execution",
        "recommended_action": "Upgrade OpenSSH to version 9.8p1 or set LoginGraceTime to 0 in sshd_config.",
        "days_open": 9,
    },
    {
        "id": "V-003",
        "cve": "CVE-2024-21887",
        "title": "Ivanti Connect Secure Command Injection",
        "severity": "Critical",
        "cvss": 9.1,
        "epss": 0.89,
        "affected_asset_id": "A-003",
        "asset_name": "Customer Identity & Federation Directory",
        "business_unit": "Digital Channels & Wealth Platform",
        "discovery_date": "2026-09-04",
        "estimated_financial_impact": 2600000.0,
        "remediation_cost": 30000.0,
        "status": "In Progress",
        "threat_vector": "Privilege Escalation",
        "recommended_action": "Execute appliance factory reset and apply latest secure firmware release package.",
        "days_open": 23,
    },
    {
        "id": "V-004",
        "cve": "CVE-2024-4577",
        "title": "PHP-CGI Windows Argument Injection (Bypass of CVE-2012-1823)",
        "severity": "High",
        "cvss": 8.8,
        "epss": 0.65,
        "affected_asset_id": "A-004",
        "asset_name": "Enterprise Analytical Data Lake (Snowflake/S3)",
        "business_unit": "Risk, Analytics & FinCrime Surveillance",
        "discovery_date": "2026-09-20",
        "estimated_financial_impact": 1450000.0,
        "remediation_cost": 12000.0,
        "status": "Open",
        "threat_vector": "Remote Code Execution",
        "recommended_action": "Update PHP binaries or configure Apache mod_rewrite disallowing best-fit mappings.",
        "days_open": 7,
    },
    {
        "id": "V-005",
        "cve": "CVE-2024-27956",
        "title": "Automatic SQL Injection in Financial Reporting Portal",
        "severity": "High",
        "cvss": 8.5,
        "epss": 0.48,
        "affected_asset_id": "A-005",
        "asset_name": "Trade Settlement & Swift Ingress Interface",
        "business_unit": "Institutional Markets & Asset Management",
        "discovery_date": "2026-09-21",
        "estimated_financial_impact": 1820000.0,
        "remediation_cost": 18000.0,
        "status": "Open",
        "threat_vector": "SQL Injection",
        "recommended_action": "Apply parameterized prepared statements across ledger query endpoint controllers.",
        "days_open": 6,
    },
    {
        "id": "V-006",
        "cve": "CVE-2024-3094",
        "title": "XZ Utils Malicious Backdoor (liblzma Supply Chain)",
        "severity": "Critical",
        "cvss": 10.0,
        "epss": 0.95,
        "affected_asset_id": "A-006",
        "asset_name": "Retail Mobile Banking Backplane",
        "business_unit": "Retail Payments & Consumer Banking",
        "discovery_date": "2026-08-30",
        "estimated_financial_impact": 1950000.0,
        "remediation_cost": 10000.0,
        "status": "Mitigated",
        "threat_vector": "Remote Code Execution",
        "recommended_action": "Downgraded xz to safe 5.4.6 release across all production container build bases.",
        "days_open": 28,
    },
]

DEMO_CONTROLS: List[Dict[str, Any]] = [
    {
        "id": "C-001",
        "name": "Phishing-Resistant MFA (FIDO2 / WebAuthn)",
        "category": "Identity & Access",
        "effectiveness_pct": 92.0,
        "coverage_pct": 78.0,
        "cost_annual": 160000.0,
        "risk_reduction_potential": 1850000.0,
        "current_maturity": 3,
        "target_maturity": 5,
        "mapped_frameworks": ["RBI Annex B.1", "SEBI CSCRF 4.1", "ISO 27001 A.9.4", "NIST PR.AC-7"],
    },
    {
        "id": "C-002",
        "name": "Zero Trust Microsegmentation for Transaction Transit",
        "category": "Cloud Security",
        "effectiveness_pct": 88.0,
        "coverage_pct": 65.0,
        "cost_annual": 420000.0,
        "risk_reduction_potential": 3100000.0,
        "current_maturity": 2,
        "target_maturity": 4,
        "mapped_frameworks": ["RBI Annex B.3", "SEBI CSCRF 6.2", "NIST PR.AC-5"],
    },
    {
        "id": "C-003",
        "name": "Automated 72-Hour Critical Patch Orchestration",
        "category": "Application Security",
        "effectiveness_pct": 85.0,
        "coverage_pct": 72.0,
        "cost_annual": 210000.0,
        "risk_reduction_potential": 2150000.0,
        "current_maturity": 3,
        "target_maturity": 4,
        "mapped_frameworks": ["RBI Annex A.4", "SEBI CSCRF 5.4", "ISO 27001 A.12.6"],
    },
    {
        "id": "C-004",
        "name": "Next-Gen EDR with Automated Ransomware Rollback",
        "category": "Endpoint Defense",
        "effectiveness_pct": 91.0,
        "coverage_pct": 89.0,
        "cost_annual": 140000.0,
        "risk_reduction_potential": 1400000.0,
        "current_maturity": 4,
        "target_maturity": 5,
        "mapped_frameworks": ["NIST DE.CM-1", "ISO 27001 A.12.2"],
    },
    {
        "id": "C-005",
        "name": "Continuous Cloud Security Posture Management (CSPM)",
        "category": "Cloud Security",
        "effectiveness_pct": 84.0,
        "coverage_pct": 81.0,
        "cost_annual": 180000.0,
        "risk_reduction_potential": 1600000.0,
        "current_maturity": 3,
        "target_maturity": 4,
        "mapped_frameworks": ["SEBI CSCRF 8.1", "NIST PR.IP-1"],
    },
]

DEMO_INITIATIVES: List[Dict[str, Any]] = [
    {
        "id": "OPT-001",
        "title": "Hardware Security Token (FIDO2) Global Enforcement",
        "category": "Identity & Access Governance",
        "cost": 160000.0,
        "expected_risk_reduction": 1850000.0,
        "rosi_pct": 1056.0,
        "bcr": 11.56,
        "difficulty": "Low",
        "time_weeks": 4,
        "business_unit": "Enterprise-Wide",
        "target_controls": ["C-001"],
        "description": "Enforce physical FIDO2 keys for 100% of privileged cloud root and production bastion sessions.",
        "annual_maintenance_cost": 25000.0,
    },
    {
        "id": "OPT-002",
        "title": "Core Banking Zero Trust Microsegmentation",
        "category": "Infrastructure Defense",
        "cost": 420000.0,
        "expected_risk_reduction": 3100000.0,
        "rosi_pct": 638.0,
        "bcr": 7.38,
        "difficulty": "High",
        "time_weeks": 16,
        "business_unit": "Core Banking & Treasury Operations",
        "target_controls": ["C-002"],
        "description": "Isolate high-value ledger databases and UPI settlement VPCs with zero-trust east-west firewall policies.",
        "annual_maintenance_cost": 65000.0,
    },
    {
        "id": "OPT-003",
        "title": "Automated 72-Hour Patch Management Pipeline",
        "category": "Vulnerability Management",
        "cost": 210000.0,
        "expected_risk_reduction": 2150000.0,
        "rosi_pct": 924.0,
        "bcr": 10.24,
        "difficulty": "Medium",
        "time_weeks": 6,
        "business_unit": "Retail Payments & Consumer Banking",
        "target_controls": ["C-003"],
        "description": "Continuous automated patch deployment for any KEV CVE with EPSS > 0.3 within 72 hours.",
        "annual_maintenance_cost": 35000.0,
    },
    {
        "id": "OPT-004",
        "title": "Next-Gen EDR Extended Host Isolation Rollback",
        "category": "Endpoint Defense",
        "cost": 140000.0,
        "expected_risk_reduction": 1400000.0,
        "rosi_pct": 900.0,
        "bcr": 10.0,
        "difficulty": "Low",
        "time_weeks": 3,
        "business_unit": "Enterprise-Wide",
        "target_controls": ["C-004"],
        "description": "Upgrade legacy agent clusters to autonomous ransomware detection with instantaneous 1-click VSS rollback.",
        "annual_maintenance_cost": 20000.0,
    },
    {
        "id": "OPT-005",
        "title": "Real-Time CSPM Cloud Drift Remediator",
        "category": "Cloud Governance",
        "cost": 180000.0,
        "expected_risk_reduction": 1600000.0,
        "rosi_pct": 789.0,
        "bcr": 8.89,
        "difficulty": "Medium",
        "time_weeks": 8,
        "business_unit": "Digital Channels & Wealth Platform",
        "target_controls": ["C-005"],
        "description": "Automated teardown and alerting for public S3 buckets, unrestricted 0.0.0.0 security groups, and wildcards.",
        "annual_maintenance_cost": 30000.0,
    },
    {
        "id": "OPT-006",
        "title": "Privileged Access Management (PAM) Vaulting",
        "category": "Identity Governance",
        "cost": 310000.0,
        "expected_risk_reduction": 1750000.0,
        "rosi_pct": 465.0,
        "bcr": 5.65,
        "difficulty": "High",
        "time_weeks": 12,
        "business_unit": "Enterprise-Wide",
        "target_controls": ["C-001"],
        "description": "Ephemeral credentials and session keystroke recording for all administrative SSH and RDP connections.",
        "annual_maintenance_cost": 50000.0,
    },
]
